### ISSUE TITLE
Serialization of int as double?

### ISSUE THREAD

**Issue by es0329** [kirisetsz/moshi-jsonapi#1]
I have a basic POJO with a property of type `int`.
```
...
@Json(name = "partner_id") int partner_id = 1;
...
```

After serialization it logs as:
```
...
"partner_id":1.0
...
```
How can I prevent conversion to `double` and send `partner_id` as `int`, the way it's modeled?

**Comment by kirisetsz** [comment]
It seems an implementation issue of the `ResourceJsonAdapter`. When serialize a `Resource` object, the adapter first convert attribute object into a JSON string. Then, the JSON is converted into a `LinkedHashMap` by the default Object converter implementation of `moshi` in which the value `1` is converted into `1.0` (a `double` value).

Newly implemented `ResourceJsonAdapter` eliminates the conversion and should work as expected.

Thanks for your help and the new release `1.0.13` is available on bintray.

**Comment by es0329** [comment]
Excellent work! Many thanks for the fix.
